from sqlalchemy.orm import Session

from app.database.models import Recipe

RECIPES = [
    {"name": "Chicken Fried Rice", "description": "A fast, savory way to rescue cooked rice and vegetables.", "cooking_time": 15, "difficulty": "Easy", "servings": 2, "ingredients": ["rice", "egg", "chicken", "carrot", "garlic", "soy sauce", "oil"], "instructions": ["Heat oil in a wide pan.", "Saute garlic and chicken until cooked through.", "Add egg and scramble gently.", "Fold in rice and carrot.", "Season with soy sauce and cook until hot."], "tags": ["Halal", "Savory", "Lunch", "Dinner", "Easy"]},
    {"name": "Garden Omelet", "description": "A fluffy egg dish that welcomes almost any leftover vegetable.", "cooking_time": 12, "difficulty": "Easy", "servings": 1, "ingredients": ["egg", "carrot", "green onion", "garlic", "oil"], "instructions": ["Whisk eggs with a pinch of salt.", "Soften vegetables in oil.", "Pour in eggs and fold when nearly set.", "Serve warm with herbs or chili."], "tags": ["Vegetarian", "Low Calorie", "Savory", "Breakfast", "Easy"]},
    {"name": "Comfort Chicken Soup", "description": "A gentle one-pot soup for chicken and vegetables that need using soon.", "cooking_time": 35, "difficulty": "Medium", "servings": 3, "ingredients": ["chicken", "carrot", "garlic", "green onion", "oil"], "instructions": ["Brown chicken lightly in a pot.", "Add garlic and carrot.", "Cover with water and simmer until chicken is tender.", "Finish with green onion and season to taste."], "tags": ["Halal", "Low Calorie", "Mild", "Dinner", "Medium"]},
    {"name": "Spicy Garlic Rice Bowl", "description": "A flexible bowl that turns leftover rice into a bright, spicy meal.", "cooking_time": 10, "difficulty": "Easy", "servings": 2, "ingredients": ["rice", "garlic", "chili", "egg", "oil"], "instructions": ["Warm oil and toast garlic with chili.", "Add rice and toss until steaming.", "Top with a fried egg.", "Taste and adjust seasoning."], "tags": ["Vegetarian", "Spicy", "Dinner", "Easy"]},
    {"name": "Tomato Egg Toast", "description": "A bright breakfast that gives soft tomatoes and eggs a second chance.", "cooking_time": 10, "difficulty": "Easy", "servings": 2, "ingredients": ["tomato", "egg", "garlic", "bread", "oil"], "instructions": ["Saute garlic and tomato until juicy.", "Add beaten eggs and stir until softly set.", "Toast the bread and spoon the eggs over it.", "Finish with pepper or chili."], "tags": ["Vegetarian", "Savory", "Breakfast", "Easy"]},
    {"name": "Rainbow Vegetable Noodles", "description": "A colorful, flexible noodle bowl for vegetables that are ready to be used.", "cooking_time": 18, "difficulty": "Easy", "servings": 2, "ingredients": ["noodles", "carrot", "green onion", "garlic", "soy sauce", "oil"], "instructions": ["Cook noodles according to the package.", "Stir-fry garlic and vegetables in oil.", "Add noodles and soy sauce.", "Toss until glossy and hot."], "tags": ["Vegetarian", "Savory", "Lunch", "Dinner", "Easy"]},
    {"name": "Chickpea Garden Salad", "description": "A no-cook salad that uses crunchy vegetables and pantry chickpeas.", "cooking_time": 8, "difficulty": "Easy", "servings": 2, "ingredients": ["chickpea", "tomato", "carrot", "green onion", "lemon"], "instructions": ["Rinse and drain the chickpeas.", "Chop the vegetables into bite-sized pieces.", "Toss everything with lemon, oil, salt, and pepper.", "Chill briefly or serve immediately."], "tags": ["Vegan", "Vegetarian", "Low Calorie", "Lunch", "Easy"]},
    {"name": "Coconut Vegetable Curry", "description": "A warming one-pot curry for mixed vegetables and pantry staples.", "cooking_time": 28, "difficulty": "Medium", "servings": 3, "ingredients": ["carrot", "tomato", "garlic", "onion", "coconut milk", "rice"], "instructions": ["Soften onion and garlic in a pot.", "Add carrot and tomato with curry spices.", "Pour in coconut milk and simmer until tender.", "Serve over warm rice."], "tags": ["Vegan", "Vegetarian", "Spicy", "Dinner", "Medium"]},
    {"name": "Creamy Potato Hash", "description": "Crisp leftover potatoes become a comforting skillet meal with egg.", "cooking_time": 20, "difficulty": "Easy", "servings": 2, "ingredients": ["potato", "egg", "onion", "garlic", "oil"], "instructions": ["Cube the potatoes and crisp them in oil.", "Add onion and garlic until golden.", "Make two wells and crack in the eggs.", "Cover until the eggs are set to your liking."], "tags": ["Vegetarian", "Savory", "Breakfast", "Easy"]},
    {"name": "Tofu Vegetable Stir-Fry", "description": "Crisp tofu and vegetables come together in a quick savory skillet.", "cooking_time": 18, "difficulty": "Easy", "servings": 2, "ingredients": ["tofu", "carrot", "green onion", "garlic", "soy sauce", "oil"], "instructions": ["Pat tofu dry and cut into cubes.", "Brown tofu in a hot pan with oil.", "Add garlic, carrot, and green onion.", "Season with soy sauce and serve hot."], "tags": ["Vegetarian", "Vegan", "Savory", "Lunch", "Dinner", "Easy"]},
    {"name": "Tuna Corn Rice Bowl", "description": "A pantry-friendly rice bowl with bright corn and a simple tuna topping.", "cooking_time": 12, "difficulty": "Easy", "servings": 2, "ingredients": ["rice", "tuna", "corn", "green onion", "egg"], "instructions": ["Warm the rice and corn together.", "Drain the tuna and season lightly.", "Top the rice with tuna and green onion.", "Add a boiled or fried egg if available."], "tags": ["High Protein", "Savory", "Lunch", "Easy"]},
    {"name": "Banana Oat Pancakes", "description": "Soft pancakes that rescue ripe bananas with a handful of pantry oats.", "cooking_time": 15, "difficulty": "Easy", "servings": 2, "ingredients": ["banana", "oats", "egg", "milk", "oil"], "instructions": ["Mash banana in a bowl.", "Mix in oats, egg, and milk.", "Rest the batter for five minutes.", "Cook small pancakes in a lightly oiled pan."], "tags": ["Vegetarian", "Breakfast", "Sweet", "Easy"]},
    {"name": "Garlic Spinach Pasta", "description": "A simple pasta that uses tender greens before they are forgotten.", "cooking_time": 20, "difficulty": "Easy", "servings": 2, "ingredients": ["pasta", "spinach", "garlic", "tomato", "oil"], "instructions": ["Cook pasta until just tender.", "Saute garlic and tomato in oil.", "Add spinach until wilted.", "Toss with pasta and a splash of cooking water."], "tags": ["Vegetarian", "Savory", "Lunch", "Dinner", "Easy"]},
    {"name": "Tomato Bean Stew", "description": "A warming, budget-friendly stew made from beans and soft tomatoes.", "cooking_time": 25, "difficulty": "Medium", "servings": 3, "ingredients": ["kidney bean", "tomato", "onion", "garlic", "carrot"], "instructions": ["Soften onion, garlic, and carrot in a pot.", "Add chopped tomato and cook until saucy.", "Stir in beans with a little water.", "Simmer until thick and season to taste."], "tags": ["Vegetarian", "Vegan", "Savory", "Dinner", "Medium"]},
    {"name": "Instant Noodle Egg Bowl", "description": "A quick upgrade for instant noodles with egg, vegetables, and aromatics.", "cooking_time": 10, "difficulty": "Easy", "servings": 1, "ingredients": ["noodles", "egg", "carrot", "green onion", "garlic", "chili"], "instructions": ["Cook the noodles with the seasoning packet.", "Add carrot and garlic during the last two minutes.", "Crack in the egg and simmer until set.", "Finish with green onion and chili."], "tags": ["Savory", "Spicy", "Lunch", "Dinner", "Easy"]},
    {"name": "Crispy Noodle Omelet", "description": "A crisp-edged omelet that turns leftover instant noodles into a filling meal.", "cooking_time": 12, "difficulty": "Easy", "servings": 1, "ingredients": ["noodles", "egg", "carrot", "green onion", "oil"], "instructions": ["Cook and drain the noodles.", "Beat eggs with carrot and green onion.", "Mix in the noodles.", "Pan-fry both sides until golden and set."], "tags": ["Savory", "Breakfast", "Lunch", "Easy"]},
    {"name": "Peanut Noodle Salad", "description": "A cool, crunchy noodle salad with a creamy pantry dressing.", "cooking_time": 15, "difficulty": "Easy", "servings": 2, "ingredients": ["noodles", "carrot", "cucumber", "peanut butter", "soy sauce", "lemon"], "instructions": ["Cook noodles, rinse under cold water, and drain well.", "Whisk peanut butter, soy sauce, and lemon with a splash of water.", "Toss noodles with carrot and cucumber.", "Drizzle over the dressing and serve chilled."], "tags": ["Vegetarian", "Savory", "Lunch", "Easy"]},
    {"name": "Chicken Noodle Soup", "description": "A comforting soup that stretches a small amount of chicken with noodles and vegetables.", "cooking_time": 25, "difficulty": "Easy", "servings": 2, "ingredients": ["noodles", "chicken", "carrot", "garlic", "green onion"], "instructions": ["Simmer chicken, carrot, and garlic in seasoned water.", "Remove chicken, shred it, and return it to the pot.", "Add noodles and cook until tender.", "Top with green onion before serving."], "tags": ["Halal", "Mild", "Lunch", "Dinner", "Easy"]},
    {"name": "Garlic Butter Noodles", "description": "A simple five-minute noodle dish for when the pantry needs a little creativity.", "cooking_time": 8, "difficulty": "Easy", "servings": 1, "ingredients": ["noodles", "garlic", "oil", "green onion", "chili"], "instructions": ["Cook noodles and reserve a little cooking water.", "Warm oil with garlic and chili.", "Toss in noodles with a splash of cooking water.", "Finish with green onion and serve immediately."], "tags": ["Vegetarian", "Spicy", "Savory", "Dinner", "Easy"]},
    {"name": "Instant Noodle Cheese Bowl", "description": "A creamy, comforting noodle bowl made in one pot.", "cooking_time": 8, "difficulty": "Easy", "servings": 1, "ingredients": ["noodles", "egg", "cheese", "green onion"], "instructions": ["Cook noodles until almost tender.", "Stir in the seasoning and cheese.", "Add the egg and simmer until cooked.", "Top with green onion and serve."], "tags": ["Savory", "Lunch", "Dinner", "Easy"]},
    {"name": "Cereal Banana Bowl", "description": "A no-cook breakfast for cereal, milk, and a ripe banana.", "cooking_time": 3, "difficulty": "Easy", "servings": 1, "ingredients": ["cereal", "milk", "banana"], "instructions": ["Pour cereal into a bowl.", "Add sliced banana.", "Pour over cold milk and enjoy immediately."], "tags": ["Vegetarian", "Breakfast", "Sweet", "Easy"]},
    {"name": "Yogurt Cereal Crunch", "description": "A quick layered snack with yogurt, cereal, and fruit.", "cooking_time": 5, "difficulty": "Easy", "servings": 1, "ingredients": ["yogurt", "cereal", "banana"], "instructions": ["Spoon yogurt into a glass or bowl.", "Add a layer of cereal and banana.", "Repeat once and serve before the cereal softens."], "tags": ["Vegetarian", "Breakfast", "Sweet", "Easy"]},
    {"name": "Peanut Banana Cereal", "description": "A filling no-cook snack with creamy peanut butter and crunchy cereal.", "cooking_time": 5, "difficulty": "Easy", "servings": 1, "ingredients": ["cereal", "banana", "peanut butter", "milk"], "instructions": ["Slice the banana into a bowl.", "Add cereal and a spoonful of peanut butter.", "Pour over milk and stir gently."], "tags": ["Vegetarian", "High Protein", "Breakfast", "Sweet", "Easy"]},
    {"name": "Cold Cereal Overnight Cup", "description": "A make-ahead cereal cup with milk, yogurt, and banana.", "cooking_time": 5, "difficulty": "Easy", "servings": 1, "ingredients": ["cereal", "milk", "yogurt", "banana"], "instructions": ["Layer cereal, yogurt, milk, and banana in a jar.", "Cover and chill for at least one hour.", "Stir before eating and add a little milk if needed."], "tags": ["Vegetarian", "Breakfast", "Sweet", "Easy"]},
    {"name": "Fruit Yogurt Cup", "description": "A cool, light dessert with yogurt, fruit, and a little honey.", "cooking_time": 5, "difficulty": "Easy", "servings": 1, "ingredients": ["yogurt", "banana", "apple", "honey", "cereal"], "instructions": ["Dice the apple and slice the banana.", "Layer fruit and yogurt in a glass.", "Top with cereal for crunch.", "Drizzle with honey and serve chilled."], "tags": ["Vegetarian", "Dessert", "Sweet", "Light", "Easy"]},
    {"name": "Banana Honey Toast", "description": "A warm, light sweet snack made from everyday breakfast ingredients.", "cooking_time": 7, "difficulty": "Easy", "servings": 1, "ingredients": ["bread", "banana", "honey", "peanut butter"], "instructions": ["Toast the bread until golden.", "Spread with peanut butter.", "Add sliced banana.", "Finish with a small drizzle of honey."], "tags": ["Vegetarian", "Dessert", "Breakfast", "Sweet", "Easy"]},
    {"name": "Chia Yogurt Pudding", "description": "A light make-ahead dessert with creamy yogurt and chia seeds.", "cooking_time": 5, "difficulty": "Easy", "servings": 2, "ingredients": ["yogurt", "milk", "chia seeds", "banana", "honey"], "instructions": ["Mix yogurt, milk, chia seeds, and honey.", "Cover and refrigerate for at least two hours.", "Stir until thick and creamy.", "Top with banana before serving."], "tags": ["Vegetarian", "Dessert", "Sweet", "Light", "Easy"]},
    {"name": "Cucumber Tuna Cups", "description": "A fresh, crunchy light meal with tuna salad served in cucumber cups.", "cooking_time": 10, "difficulty": "Easy", "servings": 2, "ingredients": ["cucumber", "tuna", "yogurt", "green onion", "lemon"], "instructions": ["Drain tuna and mix with yogurt, lemon, and green onion.", "Cut cucumber into thick rounds.", "Scoop a small center from each round.", "Fill the cucumber cups with tuna salad."], "tags": ["High Protein", "Low Calorie", "Light", "Lunch", "Easy"]},
    {"name": "Fresh Lettuce Egg Wraps", "description": "Crisp lettuce wraps filled with quick scrambled egg and vegetables.", "cooking_time": 10, "difficulty": "Easy", "servings": 2, "ingredients": ["lettuce", "egg", "carrot", "green onion", "oil"], "instructions": ["Scramble the egg with carrot and green onion.", "Wash and dry the lettuce leaves.", "Spoon the warm egg into the leaves.", "Fold and serve as light wraps."], "tags": ["Vegetarian", "Low Calorie", "Light", "Breakfast", "Easy"]},
    {"name": "Vegetable Spring Roll Bites", "description": "Light, crunchy vegetable bites for a simple snack or party plate.", "cooking_time": 18, "difficulty": "Medium", "servings": 2, "ingredients": ["spring roll wrapper", "carrot", "cucumber", "green onion", "oil"], "instructions": ["Slice the vegetables into thin sticks.", "Wrap the vegetables in spring roll wrappers.", "Seal the edges with water.", "Bake or pan-fry until crisp and serve."], "tags": ["Vegetarian", "Light", "Snack", "Medium"]},
]


def seed_db(db: Session) -> None:
    existing_names = {recipe.name for recipe in db.query(Recipe).all()}
    new_recipes = [recipe for recipe in RECIPES if recipe["name"] not in existing_names]
    if new_recipes:
        db.add_all([Recipe(**recipe) for recipe in new_recipes])
        db.commit()
